version: "3.8"
services:
  zeebe:
    image: camunda/zeebe:latest # Using 'latest' to match the version you downloaded
    container_name: zeebe
    ports:
      - "26500:26500"
    environment:
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.camunda.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
    restart: always
    volumes:
      - zeebe-data:/usr/local/zeebe/data
    networks:
      - camunda-net

  operate:
    image: camunda/operate:latest
    container_name: operate
    ports:
      - "8080:8080" # Operate on 8080
    environment:
      - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_OPERATE_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_AUTH_ENABLED=false   # <-- تعطيل الأمان
    restart: always
    depends_on:
      - elasticsearch
    networks:
      - camunda-net

  tasklist:
    image: camunda/tasklist:latest
    container_name: tasklist
    ports:
      - "8081:8080" # Tasklist on 8081
    environment:
      - CAMUNDA_TASKLIST_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_TASKLIST_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_TASKLIST_AUTH_ENABLED=false  # <-- تعطيل الأمان
    restart: always
    depends_on:
      - elasticsearch
    networks:
      - camunda-net

  elasticsearch:
    image: elasticsearch:8.12.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    restart: always
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - camunda-net

volumes:
  zeebe-data:
  es-data:

networks:
  camunda-net:
    driver: bridge